function n4ed = getN4ed(ed4n)
% n4ed
% The function getN4ed returns a nrEdges times 2 matrix. the input is
% ed4n generated by the function getEd4n. The output matrix contains
% in each row the number of the two nodes that are the endpoints of
% the edge corresponding to the row number.

% Copyright 2007 Jan Reininghaus, David Guenther
%
% This file is part of FFW.
%
% FFW is free software; you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation; either version 3 of the License, or
% (at your option) any later version.
%
% FFW is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with this program.  If not, see <http://www.gnu.org/licenses/>.


% Create nodes4edge (n4ed) to quickly produce coordinates of the new nodes
% (ed4n is symetric)
[I,J,S] = find( triu(ed4n) );
n4ed( S,: ) = [I,J];
