function ed4n = getEd4n(e4n)
% ed4n
% The function getEd4n returns a symmetric nrNodes times nrNodes
% sparse matrix. 
% NOTE: The sparse constant is bounded due to the used mesh generation.
% The input is e4n generated by the function getE4n. The
% output matrix ed4n contains the numbers of the edges between two
% nodes or zero if the two nodes are not on one edge. In the sense
% that for node j and node k the entry (j,k), and (k,j) respectively,
% is the corresponding edge number. The numbering of the edges is
% arbitrarily generated in this function. The input is n4e.

% Copyright 2007 Jan Reininghaus, David Guenther
%
% This file is part of FFW.
%
% FFW is free software; you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation; either version 3 of the License, or
% (at your option) any later version.
%
% FFW is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with this program.  If not, see <http://www.gnu.org/licenses/>.


ed4n = triu(e4n+e4n');
[I,J] = find(ed4n);
nrEdges = length(I);

ed4n = sparse(I,J,1:nrEdges,size(e4n,1),size(e4n,1));
ed4n = ed4n+ed4n';
